apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-updater
  namespace: tedy
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-updater
              image: tedyst/cloudflare-docker-updater:latest
              env:
                - name: CFKEY
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-secret
                      key: CFKEY
                - name: CFUSER
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-secret
                      key: CFUSER
                - name: CFZONE
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-secret
                      key: CFZONE
                - name: CFHOST
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-secret
                      key: CFHOST
          restartPolicy: OnFailure
