name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/tedyst/cloudflare-docker-updater/cloudflare-docker-updater:$(git rev-parse --short HEAD)
    - name: Push to GitHub docker registry
      run: docker push docker.pkg.github.com/tedyst/cloudflare-docker-updater/cloudflare-docker-updater:$(git rev-parse --short HEAD)
